### ISSUE TITLE
x-fmt/412 does not seem to be written correctly - v84 (JAR) 

### ISSUE THREAD

**Issue by ross-spencer** [exponential-decay/skeleton-test-suite-generator#4]
Possibility that variable second sequence is being written somewhere between the wildcard of the first...

**Comment by ross-spencer** [comment]
This is not an issue in DROID4 and so suggesting it's not a bug and rather, it is related to the way both DROID and SF handle containers. (May test at some point in SF without containers.)

**Comment by richardlehane** [comment]
![image](https://user-images.githubusercontent.com/157422/28495708-2c8eedd6-6f9b-11e7-8232-8c24060d6aeb.png)

**Comment by richardlehane** [comment]
![image](https://user-images.githubusercontent.com/157422/28495715-5b01869c-6f9b-11e7-9d4b-91559245e553.png)

**Comment by richardlehane** [comment]
... if you build your signatures with `roy build -doubleup` you'll get the expected match.

Where PRONOM defines both container and byte signatures for a format, the default signature file excludes the byte signatures on the basis that the container signatures should give a more accurate result and if they haven't matched there is likely an issue (& I think you raised an issue in the past where including these extraneous byte signatures was causing mismatches).

You can override this behaviour and force inclusion of the additional byte signatures with the `-doubleup` flag. It is necessary for this skeleton file because of course the container signature doesn't match it.

p.s. great to see all this weekend work you're doing on the suite Ross :)

**Comment by ross-spencer** [comment]
Great stuff! Thanks Richard.

Yep - just wanted to close these out. Think the structure is looking a little better now too now I'm using classes to store the byte structures.

I need to chat to PRONOM about sequences in the container signature for StarOffice I can't understand - once I've done that I'll release a suite for each of the legacy files and then be up to date again finally.
